### ISSUE TITLE
vulnerability is incompatible with engine 2.2.0

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#624]
```python
Internal Server Error: /vulnerability/list
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openquakeplatform/vulnerability/views.py", line 71, in list
    from openquake.commonlib import nrml, readinput
ImportError: cannot import name nrml
ERROR:django.request:Internal Server Error: /vulnerability/list
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openquakeplatform/vulnerability/views.py", line 71, in list
    from openquake.commonlib import nrml, readinput
ImportError: cannot import name nrml
```

`nrml` is now part of `hazardlib`

**Comment by daniviga** [comment]
Closed by #625
